name: Unit Tests
on:
  push:
    branches:
      - master
jobs:
  Run-GoogleTest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Configure
        working-directory: ${{github.workspace}}
        run: cmake .
      - name: Build
        working-directory: ${{github.workspace}}
        run: make
      - name: Test
        working-directory: ${{github.workspace}}   
        run: make test
